let a = 3, b = 10, c = 5;
console.log(a+b+c);
c = 10;
console.log(a+b+c);
document.write("Hello World");
document.write("2*3");
document.write(2*3);
const d = +'2';
console.log(d);
const e = 4;
console.log(e.toString());
const f = false;
console.log(String(f));